name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev
      - run: cargo build --release
